version: '3.8'

networks:
  my_restapiexpress_network:
    name: my_restapiexpress_network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_api
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    networks:
      - my_restapiexpress_network
    
  mysql_server: 
    image: mysql:latest 
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=password 
    networks:
      - my_restapiexpress_network
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  mysql: